from bs4 import BeautifulSoup
import requests
import json
import re
import os
import argparse


# --- Helpers ---

def get_id(link: str):
    return link.split('/')[-2]


def checkIfImageExistsInDirectory(image_name: str):
    return os.path.isfile('./web_assets/' + image_name)


def save_image(image_url: str, image_name: str):
    if checkIfImageExistsInDirectory(image_name):
        print('image already exists for id: {}'.format(image_name))
        return
    with open('./web_assets/' + image_name, 'wb') as handle:
        response = requests.get(image_url, stream=True)
        if not response.ok:
            print(response)
        for block in response.iter_content(1024):
            if not block:
                break
            handle.write(block)


def root_dir():
    """Returns the project root directory (two levels up from this script)."""
    return os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))


# --- Scrapers ---

def scrape_producers():
    """
    Scrape all anime producers/studios from MAL.
    Saves JSON to web_assets/ and generates Dart const map in lib/generated/.
    """
    url = 'https://myanimelist.net/anime/producer'
    print(f'[producers] Fetching {url} ...')
    soup = BeautifulSoup(requests.get(url).text, 'html.parser')

    producers = {}
    # Links are in the format: /anime/producer/ID/URL_Name
    for a in soup.select('a[href*="/anime/producer/"]'):
        href = a.get('href', '')
        match = re.search(r'/anime/producer/(\d+)/', href)
        if match:
            pid = match.group(1)
            # Display name is the link text, minus the count suffix like " (123)"
            name = re.sub(r'\s*\(\d[\d,]*\)\s*$', '', a.get_text(strip=True))
            if name and pid not in producers:
                producers[pid] = name

    # Save JSON
    json_path = os.path.join(root_dir(), 'web_assets', 'anime_producers.json')
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(producers, f, ensure_ascii=False, indent=2)

    # Generate Dart file
    dart_path = os.path.join(root_dir(), 'lib', 'generated', 'anime_producers.dart')
    _generate_map_dart('animeStudios', producers, dart_path)
    print(f'[producers] Saved {len(producers)} producers to {dart_path}')
    return producers


def scrape_magazines():
    """
    Scrape all manga magazines from MAL.
    Saves JSON to web_assets/ and generates Dart const map in lib/generated/.
    """
    url = 'https://myanimelist.net/manga/magazine'
    print(f'[magazines] Fetching {url} ...')
    soup = BeautifulSoup(requests.get(url).text, 'html.parser')

    magazines = {}
    # Links are in the format: /manga/magazine/ID/URL_Name
    for a in soup.select('a[href*="/manga/magazine/"]'):
        href = a.get('href', '')
        match = re.search(r'/manga/magazine/(\d+)/', href)
        if match:
            mid = match.group(1)
            name = re.sub(r'\s*\(\d[\d,]*\)\s*$', '', a.get_text(strip=True))
            if name and mid not in magazines:
                magazines[mid] = name

    # Save JSON
    json_path = os.path.join(root_dir(), 'web_assets', 'manga_magazines.json')
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(magazines, f, ensure_ascii=False, indent=2)

    # Generate Dart file
    dart_path = os.path.join(root_dir(), 'lib', 'generated', 'manga_magazines.dart')
    _generate_map_dart('mangaMagazines', magazines, dart_path)
    print(f'[magazines] Saved {len(magazines)} magazines to {dart_path}')
    return magazines


def _generate_map_dart(var_name: str, data: dict, out_path: str):
    """Generate a simple Dart const map file from {string_id: name}."""
    lines = []
    lines.append('// AUTO-GENERATED by python/web-utils/index.py — DO NOT EDIT')
    lines.append('')
    lines.append(f'const {var_name} = <int, String>{{')
    for sid in sorted(data.keys(), key=int):
        name = data[sid]
        lines.append(f'  {sid}: {_dart_str(name)},')
    lines.append('};')
    lines.append('')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def scrape_genres(category: str):
    """
    Scrape genres for anime or manga from MAL.
    The page has `.genre-link` sections (Genres, Explicit Genres, Themes, Demographics).
    Section names are extracted dynamically from preceding `.normal_header` elements.
    Generates a Dart map file at lib/generated/{category}_genres.dart.
    """
    url = f'https://myanimelist.net/{category}.php'
    print(f'[genres:{category}] Fetching {url} ...')
    soup = BeautifulSoup(requests.get(url).text, 'html.parser')

    genre_link_divs = soup.select('.genre-link')

    genre_groups = []
    all_genres = {}

    for div in genre_link_divs:
        # Extract genre links from this section
        genres_in_section = []
        for a in div.select('a'):
            href = a.get('href', '')
            match = re.search(rf'/{category}/genre/(\d+)/', href)
            if match:
                gid = int(match.group(1))
                name = re.sub(r'\s*\(\d[\d,]*\)\s*$', '', a.get_text(strip=True))
                if name:
                    genres_in_section.append({'id': gid, 'name': name})
                    all_genres[gid] = name

        # Skip sections with no genre links (e.g. "Adapted to Anime" on manga page)
        if not genres_in_section:
            continue

        # Find the section name from the preceding .normal_header sibling
        section_name = 'Unknown'
        prev = div.find_previous_sibling(class_='normal_header')
        if prev:
            # Clean up header text (e.g. remove "New" badge text)
            header_text = prev.get_text(strip=True)
            # Remove trailing badge words like "New"
            header_text = re.sub(r'(?:New|NEW)$', '', header_text).strip()
            if header_text:
                section_name = header_text

        genre_groups.append({
            'type': section_name,
            'genres': genres_in_section,
        })

    # Generate Dart file
    dart_path = os.path.join(root_dir(), 'lib', 'generated', f'{category}_genres.dart')
    _generate_genre_dart(category, genre_groups, all_genres, dart_path)
    print(f'[genres:{category}] Saved {len(all_genres)} genres to {dart_path}')
    return all_genres


def _genre_name_to_arb_key(name: str) -> str:
    """Convert a genre display name to an ARB key name.
    e.g. 'Slice of Life' → 'Slice_of_Life', 'Sci-Fi' → 'Sci_Fi',
         'Idols (Female)' → 'Idols_Female', 'CGDCT' → 'CGDCT'
    """
    key = name.replace(' ', '_').replace('-', '_')
    key = key.replace('(', '').replace(')', '')
    key = re.sub(r'_+', '_', key).strip('_')
    return key


def _load_arb_keys() -> set:
    """Load all key names from the English ARB file."""
    arb_path = os.path.join(root_dir(), 'lib', 'l10n', 'intl_en.arb')
    try:
        with open(arb_path, 'r', encoding='utf-8') as f:
            arb = json.load(f)
        return {k for k in arb.keys() if not k.startswith('@')}
    except FileNotFoundError:
        print(f'[warning] ARB file not found at {arb_path}')
        return set()


def _add_missing_arb_keys(missing: dict):
    """Add missing genre keys to all ARB files. Uses English value for intl_en,
    and the genre name for all other locales (as a placeholder)."""
    l10n_dir = os.path.join(root_dir(), 'lib', 'l10n')
    import glob
    arb_files = glob.glob(os.path.join(l10n_dir, 'intl_*.arb'))
    for arb_path in arb_files:
        with open(arb_path, 'r', encoding='utf-8') as f:
            arb = json.load(f)
        for key, value in missing.items():
            if key not in arb:
                arb[key] = value
        with open(arb_path, 'w', encoding='utf-8') as f:
            json.dump(arb, f, ensure_ascii=False, indent=4)
    if missing:
        print(f'[arb] Added {len(missing)} missing keys to {len(arb_files)} ARB files: {", ".join(missing.keys())}')


def _generate_genre_dart(category: str, groups: list, all_genres: dict, out_path: str):
    """Generate a Dart file with English const maps, translated genre getter, and group data."""
    prefix = 'anime' if category == 'anime' else 'manga'
    arb_keys = _load_arb_keys()

    # Build mapping: genre_id → (english_name, arb_key, has_translation)
    genre_mapping = {}
    missing_arb = {}
    for gid in sorted(all_genres.keys()):
        name = all_genres[gid]
        arb_key = _genre_name_to_arb_key(name)
        has_key = arb_key in arb_keys
        genre_mapping[gid] = (name, arb_key, has_key)
        if not has_key:
            missing_arb[arb_key] = name

    # Also check group names for ARB keys
    group_arb_keys = {}
    for g in groups:
        gname = g['type']
        gkey = _genre_name_to_arb_key(gname)
        group_arb_keys[gname] = gkey
        if gkey not in arb_keys and gkey not in missing_arb:
            missing_arb[gkey] = gname

    # Add missing keys to ARB files (genres + group names)
    if missing_arb:
        _add_missing_arb_keys(missing_arb)

    lines = []
    lines.append('// AUTO-GENERATED by python/web-utils/index.py — DO NOT EDIT')
    lines.append('')
    lines.append("import 'package:dailyanimelist/generated/l10n.dart';")
    lines.append('')

    # English const map
    lines.append(f'/// All {category} genre ID → English name.')
    lines.append(f'const {prefix}GenresEng = <int, String>{{')
    for gid in sorted(genre_mapping.keys()):
        name, _, _ = genre_mapping[gid]
        lines.append(f'  {gid}: {_dart_str(name)},')
    lines.append('};')
    lines.append('')

    # Translated map (uses S.current for all keys)
    lines.append(f'/// {category.capitalize()} genre ID → translated name (uses S.current).')
    lines.append(f'Map<int, String> get {prefix}Genres => <int, String>{{')
    for gid in sorted(genre_mapping.keys()):
        name, arb_key, _ = genre_mapping[gid]
        lines.append(f'  {gid}: S.current.{arb_key},')
    lines.append('};')
    lines.append('')

    # Genre groups (preserving section order)
    lines.append(f'/// {category.capitalize()} genres grouped by section.')
    lines.append(f'const {prefix}GenreGroupNames = <String>[')
    for g in groups:
        lines.append(f'  {_dart_str(g["type"])},')
    lines.append('];')
    lines.append('')

    lines.append(f'const {prefix}GenreGroupIds = <List<int>>[')
    for g in groups:
        ids = ', '.join(str(x['id']) for x in g['genres'])
        lines.append(f'  [{ids}],')
    lines.append('];')
    lines.append('')

    # Genre type map: translated group name → list of translated genre names
    lines.append(f'/// {category.capitalize()} genre type map: translated group name → translated genre names.')
    lines.append(f'Map<String, List<String>> get {prefix}GenreTypeMap => <String, List<String>>{{')
    for g in groups:
        gkey = group_arb_keys[g['type']]
        genre_entries = []
        for genre in g['genres']:
            gid = genre['id']
            _, arb_key, _ = genre_mapping[gid]
            genre_entries.append(f'S.current.{arb_key}')
        lines.append(f'  S.current.{gkey}: [{", ".join(genre_entries)}],')
    lines.append('};')
    lines.append('')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def _dart_str(s: str) -> str:
    """Escape a string for Dart single-quote literal."""
    s = s.replace('\\', '\\\\').replace("'", "\\'")
    return f"'{s}'"


# --- Genre description/image scraper (existing functionality) ---

def genre_page(category: str):
    """Scrape genre description text and cover images for each genre."""
    url = 'https://myanimelist.net/{}.php'.format(category)
    soup = BeautifulSoup(requests.get(url).text, 'html.parser')
    ele = soup.select('.genre-link')
    genre_desc = {}
    for i in range(min(4, len(ele))):
        e = ele[i]
        a_tags = e.select('a')
        for a in a_tags:
            link = a.attrs.get('href')
            if link is not None:
                link = 'https://myanimelist.net' + link
                genre_soup = BeautifulSoup(requests.get(link).text, 'html.parser')
                imgs = genre_soup.select('.image img')
                if imgs:
                    image_src = imgs[0].attrs.get('data-src', '')
                    print('saving for id: {} and link: {}'.format(get_id(link), image_src))
                    save_image(image_src, 'genres/{}_{}.jpg'.format(get_id(link), category))
                desc = genre_soup.select(".genre-description")
                if desc is not None and len(desc) > 0:
                    genre_desc[get_id(link)] = desc[0].text
    with open('./web_assets/genre_desc_{}.json'.format(category), 'w') as outfile:
        json.dump(genre_desc, outfile)


# --- CLI ---

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='MAL data scraper')
    parser.add_argument('--producers', action='store_true', help='Scrape anime producers/studios')
    parser.add_argument('--magazines', action='store_true', help='Scrape manga magazines')
    parser.add_argument('--genres', action='store_true', help='Scrape anime & manga genres')
    parser.add_argument('--genre-desc', choices=['anime', 'manga'], help='Scrape genre descriptions & images')
    parser.add_argument('--all', action='store_true', help='Run all scrapers (producers, magazines, genres)')
    args = parser.parse_args()

    if args.all:
        scrape_producers()
        scrape_magazines()
        scrape_genres('anime')
        scrape_genres('manga')
    else:
        if args.producers:
            scrape_producers()
        if args.magazines:
            scrape_magazines()
        if args.genres:
            scrape_genres('anime')
            scrape_genres('manga')
        if args.genre_desc:
            genre_page(args.genre_desc)

    if not any(vars(args).values()):
        parser.print_help()