name: dailyanimelist
description: Unofficial MAL Client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 2024.1.2+86

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  provider: ^6.0.2
  shared_preferences: ^2.0.5

  google_fonts: ^4.0.4
  cached_network_image: ^3.2.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.0.3
  uni_links: ^0.5.1
  shimmer: ^3.0.0
  intl: ^0.18.1
  fluttertoast: ^8.0.9
  connectivity: ^3.0.3
  carousel_slider: ^4.0.0-nullsafety.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  scrollable_positioned_list: ^0.3.8
  fl_chart: ^0.63.0
  flutter_html: ^3.0.0-beta.2
  scroll_to_index: ^3.0.1
  share: ^2.0.1
  built_collection: ^5.1.0
  flutter_local_notifications: ^16.3.1+1
  timezone: ^0.9.2
  flutter_web_browser: ^0.17.0
  flex_color_picker: ^3.3.0
  translator: ^0.1.6
  image_picker: ^1.0.4
  uuid: ^4.0.0
  dotted_border: ^2.0.0
  retry: ^3.1.0
  auto_size_text: ^3.0.0
  visibility_detector: ^0.4.0+2
  photo_view: ^0.14.0
  dio: ^5.4.0
  notification_permissions: ^0.6.1
  infinite_scroll_pagination: ^4.0.0
  line_icons: ^2.0.3
  dynamic_color: ^1.6.7
  device_info_plus: ^9.0.3
  dal_api:
    path: ./dal-api
  dal_commons:
    path: ./dal-api/dal_commons

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  restart_app: ^1.2.1
  collection: ^1.17.2
  file_picker: ^5.5.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  package_info_plus: ^4.2.0
  particle_field: ^1.0.0
  supabase_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^4.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.1.7
  intl_utils: ^2.8.4

flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cherry.jpg
    - assets/images/summer.jpg
    - assets/images/winter.png
    - assets/images/fall.jpg

    - assets/images/star.png
    - assets/images/user_dal.png
    - assets/images/myanimelist-logo.jpg
    - assets/images/mal-icon.png
    - assets/images/anime-icon.png
    - assets/images/general-icon.png
    - assets/images/anime-collage.jpg
    - assets/images/dal-black-bg.png
    - assets/images/opm.jpg
    - assets/images/user-unknown.jpg
    - assets/images/youtube.png
    - assets/images/error_image.png
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
