[package]
name = "dal-rust-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5.2"
async-recursion = "1.1.1"
axum = { version = "0.8.6", features = ["multipart"] }
axum-extra = "0.10.3"
chrono = "0.4.42"
dotenv = "0.15.0"
rand_core = "0.9.3"
reqwest = { version = "0.12.24", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
time = "0.3.44"
futures = "0.3.31"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors"] }
uuid = { version = "1.18.1", features = ["serde", "v4"] }
seahash = "4.1.0"
openssl = { version = "0.10.74", features = ["vendored"] }
aws-sdk-dynamodb = "1.95.0"
aws-config = { version = "1.8.8", features = ["behavior-version-latest"] }
simsearch = "0.3.0"
tokio-cron-scheduler = "0.15.0"

[profile.release]
overflow-checks = true

[profile.dev]
opt-level = 3
