name: dal_commons
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html_unescape: ^2.0.0
  html: ^0.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
